[tox]
envlist = py3{9,10,11,12,13}-{linux,macos,windows},coverage
skip_missing_interpreters = true
isolated_build = true
skipsdist = true

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[gh-actions:env]
PLATFORM =
    ubuntu-22.04: linux
    ubuntu-24.04: linux
    macos-latest: macos
    windows-latest: windows

[base]
deps =
    pip>=21.1
    setuptools_scm[toml]

[build]
deps =
    pip>=21.1
    build
    twine

[testenv]
skip_install = true
install_command = pip install {opts} {packages}
#base_python = 3.12

setenv =
    COVERAGE_FILE = .coverage.{envname}
    TEST_INTEGRATION = True

passenv =
    DISPLAY
    XAUTHORITY
    HOME
    USERNAME
    USER
    XDG_*
    CI
    OS
    PYTHONIOENCODING
    PIP_DOWNLOAD_CACHE

allowlist_externals =
    bash

deps =
    {[base]deps}
    sniffer
    -e .[test,cov]

commands =
    python -m pytest \
    --deselect=doorstop/cli/tests/test_all.py::TestClear::test_clear_tree \
    --deselect=doorstop/cli/tests/test_all.py::TestReview::test_review_tree \
    --deselect=doorstop/cli/tests/test_all.py::TestPublish::test_publish_tree_html \
    --deselect=doorstop/core/publishers/tests/test_publisher_html_doc.py::TestPublisherFullDocument::test_publish_html_tree_copies_assets \
    --deselect=doorstop/core/publishers/tests/test_publisher_latex_doc.py::TestPublisherFullDocument::test_publish_document_no_headings_with_latex_data \
    --deselect=doorstop/core/publishers/tests/test_publisher_latex_doc.py::TestPublisherFullDocument::test_publish_latex_tree_copies_assets \
    --deselect=doorstop/server/tests/test_all.py::TestServer::test_get_traceabilty \
    --deselect=doorstop/server/tests/test_api.py::TestAPIHtml::test_get_traceabilty \
    --deselect=doorstop/server/tests/test_api.py::TestAPIHtml::test_get_traceabilty_no_html \
    --deselect=doorstop/server/tests/test_api.py::TestAPIHtml::test_get_traceabilty_slash \
    --deselect=doorstop/server/tests/test_api.py::TestAPIjson::test_get_traceabilty \
    --deselect=doorstop/server/tests/test_server.py::TestMain::test_main_version \
    -v . \
    --capture={posargs:"fd"} \
    --doctest-modules \
    --cov=doorstop \
    --cov-branch \
    --cov-report term-missing

[testenv:coverage]
basepython = python3

skip_install =
    true

allowlist_externals =
    bash

deps =
    coverage

commands =
    bash -c 'coverage combine .coverage.py*'
    coverage xml

depends =
    py39
    py310
    py311
    py312
    py313

[coverage:report]
omit =
    */gui/main.py
    */gui/application.py
    */gui/utilTkinter.py
    */gui/widget.py

[coverage:run]
parallel=True
# toml omit settings appear to be ignored?
omit =
    */tests/*

[testenv:dev]
passenv =
    pythonLocation
    CI
    PYTHONIOENCODING
    PIP_DOWNLOAD_CACHE

deps =
    {[base]deps}
    -e .

commands =
    doorstop --version

[testenv:lint]
passenv =
    CI
    PYTHONIOENCODING

setenv = PYTHONPATH = {toxinidir}

deps =
    {[base]deps}
    astroid
    pylint
    .

commands =
    pylint -j 4 \
    --rcfile=.pylint.ini \
    --score=yes \
    --fail-under=9.9 \
    doorstop {posargs}

[testenv:build]
skip_install = true

passenv =
    pythonLocation
    CI
    PYTHONIOENCODING
    PIP_DOWNLOAD_CACHE

deps =
    {[build]deps}

commands =
    python -m build .
    twine check dist/*

[testenv:check]
skip_install = true
passenv = CI

allowlist_externals = bash

deps =
    pip>=21.1

commands =
    python -m pip install doorstop --force-reinstall --pre --prefer-binary -f dist/
    python -m pip show -f doorstop
    doorstop --version

[testenv:mypy]
skip_install = true

setenv = PYTHONPATH = {toxinidir}

allowlist_externals =
    {[testenv:dev]allowlist_externals}

deps =
    {[base]deps}
    # munch-stubs
    mypy
    types-markdown
    types-pyyaml
    types-requests
    types-setuptools
    .

commands =
    python -m mypy --config-file=.mypy.ini doorstop/ {posargs}

[testenv:black]
skip_install = true

setenv = PYTHONPATH = {toxinidir}

deps =
    {[base]deps}
    black

commands =
    black -v -S doorstop/ {posargs}

[testenv:isort]
skip_install = true

setenv = PYTHONPATH = {toxinidir}

deps =
    {[base]deps}
    isort

commands =
    python -m isort doorstop/

[testenv:clean]
skip_install = true
allowlist_externals = bash

deps =
    pip>=21.1

commands =
    bash -c 'rm -rf build/ dist/ __pycache__/ doorstop/tests/__pycache__/ */__pycache__/ .coverage.* *.egg-info/ docs/source/api/'
